### ISSUE TITLE
Namespace prefix xsi for type on AttributeValue is not defined

### ISSUE THREAD

**Issue by busla** [onelogin/python3-saml#107]
I understand that this error is not related to this package but it would be great if `OneLogin_Saml2_XML._parse_etree` could handle namespace prefixes since lxml doesn´t seem to catch them.

```xml
<Attribute Name="ssn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="ssn"><AttributeValue xsi:type="xsd:string">some-ssn-value</AttributeValue></Attribute>
```

```python
Traceback (most recent call last):
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/levy/Code/python3-saml/demo-django/demo/views.py", line 35, in login
    auth.process_response()
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/onelogin/saml2/auth.py", line 102, in process_response
    response = OneLogin_Saml2_Response(self.__settings, self.__request_data['post_data']['SAMLResponse'])
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/onelogin/saml2/response.py", line 39, in __init__
    self.document = OneLogin_Saml2_XML.to_etree(self.response)
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/onelogin/saml2/xml_utils.py", line 65, in to_etree
    return OneLogin_Saml2_XML._parse_etree(xml)
  File "/Users/levy/Code/python3-saml/venv/lib/python3.6/site-packages/defusedxml/lxml.py", line 143, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 47
lxml.etree.XMLSyntaxError: Namespace prefix xsi for type on AttributeValue is not defined, line 47, column 39
```

**Comment by busla** [comment]
```xml
<Attribute Name="ssn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="ssn">
 <AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">some-ssn-value</AttributeValue>
 </Attribute>
```
Ok, lxml handles this properly if the xsi namespace is also defined.

**Comment by pitbulk** [comment]
Can you provide an example of the SAMLResponse that fails (remove signature content if you want )?

**Comment by busla** [comment]
thanks for looking into this!

```xml
<Response ID="removed" Version="2.0" IssueInstant="2018-08-24T18:06:44.9968865Z" Destination="removed">
    <Issuer>some-issuer</Issuer>
    <Signature>
        <SignedInfo>
            <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
            <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
            <Reference URI="">
                <Transforms>
                    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                </Transforms>
                <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <DigestValue>removed</DigestValue>
            </Reference>
        </SignedInfo>
        <SignatureValue>removed</SignatureValue>
        <KeyInfo>
            <X509Data>
                <X509Certificate>removed</X509Certificate>
            </X509Data>
        </KeyInfo>
    </Signature>
    <Status>
        <StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </Status>
    <Assertion Version="2.0" ID="removed" IssueInstant="2018-08-24T18:06:44.9968865Z">
        <Issuer>some-issuer</Issuer>
        <Subject>
            <NameID NameQualifier="removed" />
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData Address="10.121.57.25" NotOnOrAfter="2018-08-24T18:11:44.9968865Z" Recipient="removed" />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2018-08-24T18:06:34.9968865Z" NotOnOrAfter="2018-08-24T18:11:44.9968865Z">
            <AudienceRestriction>
                <Audience>removed</Audience>
            </AudienceRestriction>
        </Conditions>
        <AuthnStatement AuthnInstant="2018-08-24T18:06:44.9968865Z">
            <SubjectLocality Address="212.30.225.139" />
            <AuthnContext>
                <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:TLSClient</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
        <AttributeStatement>
            <Attribute Name="ssn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="ssn">
                <AttributeValue xsi:type="xsd:string">some-ssn</AttributeValue>
            </Attribute>
        </AttributeStatement>
    </Assertion>
</Response>
```

**Comment by pitbulk** [comment]
In the previous XML you are defining
```
<AttributeValue xsi:type="xsd:string">some-ssn</AttributeValue>
```
but xsi namespace was not defined on the XML. So the XML can be consider invalid.

**Comment by busla** [comment]
Thanks, learned alot today after reading the saml2 specs.
