### ISSUE TITLE
How to run the Flask project?

### ISSUE THREAD

**Issue by togakangaroo** [onelogin/python3-saml#98]
I'm unclear how to run the flask demo project. I do

    pip install -r requirements.txt

and then try

   python index.js

Predictably I get an error 

```
Traceback (most recent call last):
  File "index.py", line 8, in <module>
    from onelogin.saml2.auth import OneLogin_Saml2_Auth
ModuleNotFoundError: No module named 'onelogin
```

There is no onelogin in requirements. How am I supposed to run this?

**Comment by pitbulk** [comment]
In requirements.txt there are dependencies of the flask project.

Is supposed that you previously executed a:
```
pip install onelogin
```

Or if you downloaded the code, you executed
```
python setup.py install
```

**Comment by togakangaroo** [comment]
Hmm, no this isn't working

```
~/code/python3-saml/demo-flask $ pip install onelogin
Collecting onelogin
  Downloading https://files.pythonhosted.org/packages/e7/ed/f5ef64dd79fac77f118daac50e11971280508f2c3ec434e255b2edb1c9d4/onelogin-1.3.1-py3-none-any.whl
Collecting requests==2.18.2 (from onelogin)
  Downloading https://files.pythonhosted.org/packages/cf/fa/31b222e4b44975de1b5ac3e1a725abdfeb00e0d761567ab426ee28a7fc73/requests-2.18.2-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 601kB/s 
Collecting python-dateutil==2.6.1 (from onelogin)
  Downloading https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 871kB/s 
Collecting lxml==3.8.0 (from onelogin)
  Downloading https://files.pythonhosted.org/packages/9d/50/f41b3d37eaa4db8bb9d2ce2b04d2d3f229b787cb83281df0c8ee33d6c3e9/lxml-3.8.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.8MB)
    100% |████████████████████████████████| 7.9MB 796kB/s 
Collecting defusedxml==0.5.0 (from onelogin)
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.2->onelogin)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 849kB/s 
Collecting idna<2.6,>=2.5 (from requests==2.18.2->onelogin)
  Downloading https://files.pythonhosted.org/packages/11/7d/9bbbd7bb35f34b0169542487d2a8859e44306bb2e6a4455d491800a5621f/idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 738kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.2->onelogin)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 827kB/s 
Requirement already satisfied: certifi>=2017.4.17 in /Users/gmauer/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests==2.18.2->onelogin) (2018.4.16)
Requirement already satisfied: six>=1.5 in /Users/gmauer/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from python-dateutil==2.6.1->onelogin) (1.11.0)
Installing collected packages: urllib3, idna, chardet, requests, python-dateutil, lxml, defusedxml, onelogin
  Found existing installation: python-dateutil 2.7.2
    Uninstalling python-dateutil-2.7.2:
      Successfully uninstalled python-dateutil-2.7.2
Successfully installed chardet-3.0.4 defusedxml-0.5.0 idna-2.5 lxml-3.8.0 onelogin-1.3.1 python-dateutil-2.6.1 requests-2.18.2 urllib3-1.22
~/code/python3-saml/demo-flask $ python index.py 
Traceback (most recent call last):
  File "index.py", line 8, in <module>
    from onelogin.saml2.auth import OneLogin_Saml2_Auth
ModuleNotFoundError: No module named 'onelogin.saml2'
~/code/python3-saml/demo-flask $ 
```

btw `requirements.txt` contains only flask

**Comment by pitbulk** [comment]
are you using a virtualenv for your flask app and is your virtualenv enabled when you installed the onelogin package?

**Comment by pitbulk** [comment]
Check this documentation: http://calebbron.com/tech/saml-in-flask.html

**Comment by platipusica** [comment]
I can report from here: https://github.com/onelogin/python3-saml/issues/96

that Flask does work with more deps tho:

 2038  python setup.py
 2039  python setup.py install
 2040  pip install libxmlsec1-dev pkg-config
 2041  sudo apt install libxmlsec1-dev pkg-config
 2042  python setup.py install
 2043  sudo apt install python3-devel
 2044  sudo apt install python3-dev
 2045  python setup.py install
